apiVersion: v1
kind: ConfigMap
metadata:
  name: petcare-config
  namespace: petcare
data:
  AWS_REGION: "us-east-1"
  MONGO_URI: "mongodb://mongodb:27017/petcare"
  MONGO_DATABASE: "petcare"
  BACKEND_PORT: "8080"
  FRONTEND_API_URL: "http://backend:8080"
  SNS_TOPIC_ARN: ""
  SQS_QUEUE_URL: ""
  LAMBDA_FUNCTION_NAME: "petcare-cloud-processar-agendamento"
