apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: petcare
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: petcare-secrets
  namespace: petcare
type: Opaque
stringData:
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/673020849727/petcare-cloud-agendamentos-queue"
  SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:673020849727:petcare-cloud-agendamentos-topic"
  MONGO_URI: "mongodb://mongodb:27017/petcare"
