apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: petcare
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: petcare-secrets
  namespace: petcare
type: Opaque
stringData:
  # Preencha com os valores do output do Terraform:
  #   terraform output sqs_queue_url
  #   terraform output sns_topic_arn
  SQS_QUEUE_URL: ""
  SNS_TOPIC_ARN: ""
  MONGO_URI: "mongodb://mongodb:27017/petcare"
