apiVersion: v1
kind: ConfigMap
metadata:
  name: petcare-config
  namespace: petcare
data:
  MONGO_URI: "mongodb://mongodb:27017/petcare"
  REDIS_URL: "redis://redis:6379"
  AWS_REGION: "us-east-1"
  PORT: "4000"
  # Substitua com os ARNs reais após o terraform apply
  SNS_TOPIC_ARN: "arn:aws:sns:us-east-1:ACCOUNT_ID:petcare-cloud-agendamentos-topic"
  SQS_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/ACCOUNT_ID/petcare-cloud-agendamentos-queue"
  S3_BUCKET: "petcare-cloud-pet-images-XXXX"
  LAMBDA_FUNCTION_NAME: "petcare-cloud-processar-agendamento"
  PROJECT_NAME: "petcare-cloud"
